### PR TITLE
Written install-porter-on-k3s-en.

### PR DESCRIPTION
**Pull request by Patrick-LuoYu**
Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@duanjiong @zheng1  Could you pls help to review it?

**Comment by duanjiong** [comment]
It seems that the link to the picture inside the article is not working?

**Comment by Patrick-LuoYu** [comment]
The image paths are formatted according to the porterlb.io website. Everything should be fine if you run Hugo.

**Pull request merged**
